title: City of Lebanon, NH Zoning Ordinance (Beta)
description: Exploring the use of Github Pages for our zoning ordinance.
theme: just-the-docs

url: https://github.com/melbamorph/zoning.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
